import { Button } from "@/components/ui/button"

export default function LandingPage() {
  return (
    <div>
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />
      <Button>Click me</Button><br />

    </div>
  );
}
